version: "3.8"

services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/scripts:/docker-entrypoint-initdb.d
      - ./my.cnf:/etc/mysql/conf.d/my.cnf

  backend:
    build:
      context: ./questionBE
      dockerfile: Dockerfile
    env_file:
      - ./questionBE/config/.env.docker
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    depends_on:
      - db

  frontend:
    build:
      context: ./questionFE
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  db_data:
